package com.example.convenemusic.ui

object TopArtists {
    val names = listOf(
        "Taylor Swift", "Drake", "The Weeknd", "Billie Eilish", "Arijit Singh",
        "Ed Sheeran", "Eminem", "Bruno Mars", "Coldplay", "BTS",
        "Dua Lipa", "Ariana Grande", "Post Malone", "Adele", "Justin Bieber",
        "Imagine Dragons", "Kendrick Lamar", "Rihanna", "Lady Gaga", "Bad Bunny",
        "Beyonce", "Kanye West", "SZA", "Olivia Rodrigo", "Harry Styles",
        "A.R. Rahman", "Shreya Ghoshal", "Pritam", "Atif Aslam", "Sonu Nigam",
        "Lata Mangeshkar", "Kishore Kumar", "Mohit Chauhan", "Neha Kakkar", "Diljit Dosanjh",
        "Sidhu Moose Wala", "Karan Aujla", "AP Dhillon", "Shubh", "Yo Yo Honey Singh",
        "Jubin Nautiyal", "KK", "Udit Narayan", "Alka Yagnik", "Kumar Sanu",
        "Sachet Tandon", "Parampara Tandon", "Vishal-Shekhar", "Sachin-Jigar", "Amit Trivedi",
        "Anirudh Ravichander", "Ilaiyaraaja", "SP Balasubrahmanyam", "K.S. Chithra", "Sid Sriram",
        "Vijay Prakash", "Armaan Malik", "Amaal Mallik", "Badshah", "DIVINE",
        "Raftaar", "King", "Prateek Kuhad", "Ritviz", "When Chai Met Toast",
        "Sanam", "The Local Train", "Lucky Ali", "Ali Sethi", "Nusrat Fateh Ali Khan",
        "Abida Parveen", "Coke Studio", "BLACKPINK", "NewJeans", "SEVENTEEN",
        "Stray Kids", "EXO", "TWICE", "Red Velvet", "IVE",
        "LE SSERAFIM", "ITZY", "ENHYPEN", "TXT", "NCT 127",
        "NCT DREAM", "ATEEZ", "GOT7", "Monsta X", "BIGBANG",
        "IU", "PSY", "G-Dragon", "Jungkook", "V",
        "Jimin", "RM", "Agust D", "J-Hope", "Jin",
        "Doja Cat", "Miley Cyrus", "Tate McRae", "Sabrina Carpenter", "Lana Del Rey",
        "Noah Kahan", "Zach Bryan", "Morgan Wallen", "Luke Combs", "Kacey Musgraves",
        "Chris Stapleton", "Lainey Wilson", "Carrie Underwood", "Dolly Parton", "Shania Twain",
        "Megan Thee Stallion", "Nicki Minaj", "Cardi B", "Ice Spice", "Latto",
        "Travis Scott", "Future", "Metro Boomin", "21 Savage", "J. Cole",
        "Lil Wayne", "Jay-Z", "Nas", "Dr. Dre", "Snoop Dogg",
        "Tupac Shakur", "The Notorious B.I.G.", "50 Cent", "ASAP Rocky", "Tyler, The Creator",
        "Frank Ocean", "Childish Gambino", "Anderson .Paak", "Mac Miller", "Juice WRLD",
        "XXXTENTACION", "Lil Uzi Vert", "Playboi Carti", "Lil Baby", "DaBaby",
        "Roddy Ricch", "Polo G", "Pop Smoke", "Jack Harlow", "Central Cee",
        "Dave", "Stormzy", "Skepta", "J Hus", "Little Simz",
        "Sam Smith", "Lewis Capaldi", "Hozier", "James Arthur", "John Legend",
        "Charlie Puth", "Shawn Mendes", "Camila Cabello", "Selena Gomez", "Demi Lovato",
        "Halsey", "P!nk", "Kelly Clarkson", "Christina Aguilera", "Britney Spears",
        "Madonna", "Celine Dion", "Whitney Houston", "Mariah Carey", "Janet Jackson",
        "Michael Jackson", "Prince", "Stevie Wonder", "Elton John", "Billy Joel",
        "Paul McCartney", "John Lennon", "George Michael", "David Bowie", "Queen",
        "The Beatles", "The Rolling Stones", "Pink Floyd", "Led Zeppelin", "AC/DC",
        "Metallica", "Nirvana", "Pearl Jam", "Foo Fighters", "Red Hot Chili Peppers",
        "Green Day", "Linkin Park", "Evanescence", "Paramore", "My Chemical Romance",
        "Fall Out Boy", "Panic! At The Disco", "Twenty One Pilots", "Arctic Monkeys", "The 1975",
        "The Killers", "Muse", "Radiohead", "Oasis", "Blur",
        "The Smiths", "The Cure", "Depeche Mode", "U2", "Bon Jovi",
        "Guns N' Roses", "Aerosmith", "KISS", "Def Leppard", "Scorpions",
        "Journey", "Fleetwood Mac", "Eagles", "The Doors", "Jimi Hendrix",
        "Bob Dylan", "Bruce Springsteen", "Elvis Presley", "Johnny Cash", "Willie Nelson",
        "Neil Young", "Simon & Garfunkel", "Phil Collins", "Genesis", "Sting",
        "The Police", "Dire Straits", "Toto", "Chicago", "Creedence Clearwater Revival",
        "Maroon 5", "OneRepublic", "Train", "The Script", "Snow Patrol",
        "Keane", "Kings of Leon", "Imagine Dragons", "Bastille", "Mumford & Sons",
        "Florence + The Machine", "Lorde", "Tame Impala", "Gorillaz", "Daft Punk",
        "Calvin Harris", "David Guetta", "Avicii", "Martin Garrix", "Tiesto",
        "The Chainsmokers", "Marshmello", "Skrillex", "Diplo", "Major Lazer",
        "Zedd", "Kygo", "Alan Walker", "Swedish House Mafia", "Disclosure",
        "ODESZA", "Fred again..", "Sia", "Ellie Goulding", "Bebe Rexha",
        "Rita Ora", "Anne-Marie", "Jessie J", "Charli XCX", "Troye Sivan",
        "Troye Sivan", "Conan Gray", "Benson Boone", "JVKE", "Lauv",
        "LANY", "Cigarettes After Sex", "The Neighbourhood", "Glass Animals", "Foster the People",
        "MGMT", "Vampire Weekend", "Phoenix", "Two Door Cinema Club", "The Strokes",
        "The White Stripes", "The Black Keys", "The Lumineers", "Bon Iver", "Sufjan Stevens",
        "Phoebe Bridgers", "boygenius", "Mitski", "Clairo", "beabadoobee",
        "Rex Orange County", "Steve Lacy", "Daniel Caesar", "Giveon", "Khalid",
        "The Kid LAROI", "Troye Sivan", "Miguel", "Usher", "Chris Brown",
        "Ne-Yo", "Alicia Keys", "Mary J. Blige", "Lauryn Hill", "Erykah Badu",
        "Sade", "Toni Braxton", "TLC", "Destiny's Child", "Spice Girls",
        "Backstreet Boys", "NSYNC", "One Direction", "Jonas Brothers", "5 Seconds of Summer",
        "Little Mix", "Fifth Harmony", "BLACKPINK", "Little Dragon", "Clean Bandit",
        "Rudimental", "Years & Years", "Mabel", "Zara Larsson", "Tove Lo",
        "Robyn", "ABBA", "A-ha", "Roxette", "Ace of Base",
        "Shakira", "Enrique Iglesias", "Ricky Martin", "Jennifer Lopez", "Pitbull",
        "Daddy Yankee", "J Balvin", "Maluma", "Karol G", "Rauw Alejandro",
        "Ozuna", "Anuel AA", "Feid", "Myke Towers", "Nicky Jam",
        "Don Omar", "Wisin & Yandel", "Becky G", "Rosalia", "Manu Chao",
        "Luis Fonsi", "Camilo", "Sebastian Yatra", "CNCO", "Morat",
        "Mana", "Juanes", "Carlos Vives", "Marc Anthony", "Gloria Estefan",
        "Selena", "Bad Bunny", "Peso Pluma", "Natanael Cano", "Grupo Frontera",
        "Fuerza Regida", "Junior H", "Eslabon Armado", "Carin Leon", "Christian Nodal",
        "Aventura", "Romeo Santos", "Prince Royce", "Juan Luis Guerra", "Shakira",
        "Burna Boy", "Wizkid", "Davido", "Rema", "Tems",
        "Ayra Starr", "Asake", "Omah Lay", "Fireboy DML", "CKay",
        "Tiwa Savage", "Yemi Alade", "Mr Eazi", "Stonebwoy", "Shatta Wale",
        "Fela Kuti", "Angelique Kidjo", "Miriam Makeba", "Amadou & Mariam", "Tinariwen",
        "Bob Marley & The Wailers", "Sean Paul", "Shaggy", "Damian Marley", "Chronixx",
        "Protoje", "Koffee", "Toots and the Maytals", "Jimmy Cliff", "Buju Banton",
        "The Wailers", "UB40", "Sublime", "SOJA", "Rebelution",
        "Hillsong Worship", "Elevation Worship", "Maverick City Music", "Lauren Daigle", "Chris Tomlin",
        "Kirk Franklin", "CeCe Winans", "Amy Grant", "Michael W. Smith", "Casting Crowns",
        "Andrea Bocelli", "Luciano Pavarotti", "Sarah Brightman", "Josh Groban", "Il Divo",
        "Ludovico Einaudi", "Yiruma", "Max Richter", "Hans Zimmer", "John Williams",
        "Ennio Morricone", "Joe Hisaishi", "Ramin Djawadi", "Adele", "Norah Jones",
        "Diana Krall", "Michael Buble", "Frank Sinatra", "Ella Fitzgerald", "Louis Armstrong",
        "Billie Holiday", "Nina Simone", "Miles Davis", "John Coltrane", "Herbie Hancock",
        "The Weeknd", "Kendrick Lamar", "Ty Dolla Sign", "Pusha T", "Big Sean",
        "Meek Mill", "Rick Ross", "Gucci Mane", "Young Thug", "Gunna",
        "Migos", "Quavo", "Offset", "Takeoff", "Moneybagg Yo",
        "NLE Choppa", "Kodak Black", "Trippie Redd", "Ski Mask the Slump God", "Don Toliver",
        "Yeat", "Ken Carson", "Destroy Lonely", "Icewear Vezzo", "GloRilla",
        "Flo Milli", "Saweetie", "Doja Cat", "Summer Walker", "Jhene Aiko",
        "Kehlani", "Victoria Monet", "Tinashe", "Normani", "Chloe",
        "H.E.R.", "Ari Lennox", "Brent Faiyaz", "PARTYNEXTDOOR", "Bryson Tiller",
        "Tory Lanez", "6LACK", "d4vd", "PinkPantheress", "FKA twigs",
        "Grimes", "Lykke Li", "MO", "Aurora", "Of Monsters and Men",
        "Sigur Ros", "Bjork", "The Cranberries", "Sinead O'Connor", "Enya",
        "The Corrs", "Westlife", "Boyzone", "Take That", "Robbie Williams",
        "Duran Duran", "Pet Shop Boys", "New Order", "Joy Division", "Talking Heads",
        "Blondie", "Ramones", "Sex Pistols", "The Clash", "Iggy Pop",
        "Pixies", "Sonic Youth", "Smashing Pumpkins", "Soundgarden", "Alice in Chains",
        "System of a Down", "Slipknot", "Korn", "Limp Bizkit", "Rage Against the Machine",
        "Tool", "Nine Inch Nails", "Rammstein", "Bring Me The Horizon", "Arijit Singh",
        "Tame Impala", "Jungle", "Khruangbin", "Vulfpeck", "Snarky Puppy",
        "Jacob Collier", "Thundercat", "Flying Lotus", "Kaytranada", "Mura Masa",
        "Flume", "Porter Robinson", "Madeon", "Aphex Twin", "The Chemical Brothers",
        "The Prodigy", "Fatboy Slim", "Massive Attack", "Portishead", "Bonobo",
        "Zero 7", "Air", "Moby", "Enigma", "Enya",
        "AURORA", "Birdy", "James Blake", "Sampha", "Arlo Parks",
        "Raye", "Sigrid", "Maisie Peters", "Gracie Abrams", "Teddy Swims"
    ).distinct().take(500)
}
